name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["kind/enhancement","feature" ,"untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Please, fill this form to help us improve the project.
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Please describe below a clear and concise exposition of what you want to happen.
      placeholder: Tell us what you want to happen...
    validations:
      required: true
  - type: textarea
    id: related-to-a-problem?
    attributes:
      label: Is your feature request related to a problem?
      description: Please provide below a clear and concise description of what the problem is.
      placeholder: For example, "I'm always frustrated when...
    validations:
      required: false
  - type: textarea
    id: describe-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Please let us know about other solutions you've tried or researched.
      placeholder: Tell us about alternatives you've considered...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      placeholder: You might want to link to related issues here, if you haven't already...
      description: |
        Please add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false